### Arrays In Python 

In [ ]:
# In general an array is a list in python but in data science we use numpy arrays which are more efficient than lists.
arr1 = ['pune',"mumbai","surat","kolkata",'bihar',"jaipur",'chennai']

In [2]:
type(arr1)

list

In [3]:
arr1[0]

'pune'

In [4]:
import numpy as np

In [5]:
arr2 = np.array([10,20,30,40,50])

In [6]:
type(arr2)

numpy.ndarray

In [7]:
print(arr2)

[10 20 30 40 50]


In [8]:
arr3 = np.array([100,200,300,400,500])

In [9]:
print(arr3)

[100 200 300 400 500]


- one-dimensional array is the collection of 0th dimensional array --> Eg - [5,2,1]
- two-dimensional array is the collection of one dimensional array --> Eg - [[1,2,3],[4,5,6]]
- three-dimensional array is the collection of two-dimensional array --> Eg - [[[2,3,1],[4,5,6]],[[7,8,9],[10,11,12]]]
- zero-dimensional array is the collection of 1 element --> Eg - 5

In [10]:
import numpy as np
a0 = np.array(10)

In [11]:
print(a0)

10


In [ ]:
a0.ndim # ndim shows the dimension of the array. Here it is 0 because it is a scalar value.

0

In [13]:
a1 = np.array([1,2,3,4,5,6,7,8,9,10])

In [14]:
a1.ndim

1

In [17]:
a2 = np.array([[1,2,3],[4,5,6],[8,9,10]])

In [18]:
a2.ndim

2

In [19]:
print(a2)

[[ 1  2  3]
 [ 4  5  6]
 [ 8  9 10]]


In [20]:
a3 = np.array([[[1,2,3],[4,5,6],[8,9,10]],[[11,12,13],[14,15,16],[18,19,20]]])

In [21]:
a3.ndim

3

In [ ]:
print(a3) # ndim and ndmin are different 

[[[ 1  2  3]
  [ 4  5  6]
  [ 8  9 10]]

 [[11 12 13]
  [14 15 16]
  [18 19 20]]]


In [ ]:
a4 = np.array([4,44,444,4444],ndmin=4) # ndmin is used to specify the minimum number of dimensions of the array.

In [28]:
print(a4)

[[[[   4   44  444 4444]]]]
